### ISSUE TITLE
browserless does not seem to have a free tier. I used scrapingant instead

### ISSUE THREAD

**Issue by arjunkrishna** [joaomdmoura/crewAI-examples#33]
browserless.io does not seem to have a free tier... so i replaced it with scrapingant.

used this in browser_tools.py and added the SCRAPINGANT_API_KEY api key in .env file.
 url = f"https://api.scrapingant.com/v2/general?x-api-key={os.environ['SCRAPINGANT_API_KEY']}"

**Comment by jacopo-chevallard** [comment]
A pull request and some edits to the README might be a good idea so that people don't look for the (non existing) Browserless free tier
