### ISSUE TITLE
Typo in stock_analysis README

### ISSUE THREAD

**Issue by prabha-git** [joaomdmoura/crewAI-examples#37]
https://github.com/joaomdmoura/crewAI-examples/tree/main/stock_analysis#integrating-ollama-with-crewai
```
ollama_openhermes = Ollama(model="agent")
```
Should be 'openhermes'
ollama_openhermes = Ollama(model="openhermes")

**Comment by Biancamazzi** [comment]
https://github.com/joaomdmoura/crewAI-examples/pull/38
