### ISSUE TITLE
Inserting in ChromaDB ERROR

### ISSUE THREAD

**Issue by saibhaskerraju** [joaomdmoura/crewAI-examples#67]
Hello Team,

I recently started using CrewAI and my task is to read contents on various PDFs for a particular query and later generate a summary of it.

I am using the code from here : https://docs.crewai.com/core-concepts/Tools/#using-crewai-tools .
however, my code has ONE agent with two tools i.e. DirectoryReadTool and PDFSearchTool 

`writer = Agent(
    role='Content Writer',
    goal='Write amazing, super engaging blog post about BMW',
    backstory='A skilled writer with a passion for Automobiles/cars/vechiles.',
    tools=[docs_tools, pdf_search_tool],
    verbose=True,
    llm=azure_llm
)`

when I try to run the program. this is the output I see

<img width="1669" alt="image" src="https://github.com/joaomdmoura/crewAI-examples/assets/11057669/e136073c-0919-4c48-860c-ad1c581880da">

The program generates a summary as instructed but i see this error. Can someone please suggest me what to do ?

Python : 3.11
Host : Docker
Libraries : latest version of crewai and crewai[tools]

**Comment by saibhaskerraju** [comment]
I changed the embeddings to Azure OpenAI and it solved my issue

**Comment by kaushalpowar** [comment]
> I changed the embeddings to Azure OpenAI and it solved my issue

Can you please share how did you change the embeddings from chroma to Azure OpenAI. I am facing the same issue with `GithubSearchTool`

**Comment by saibhaskerraju** [comment]
Hey @kaushalpowar, I think the new version of crewai gives you the flexibility to change the embedding and LLM via a configuration. please check the latest docs. in case, you can change for some reason, this is what i did.

navigate to this file : lib/python3.11/site-packages/embedchain/embedder/openai.py

replace the content with the below

`import os
from typing import Optional
from chromadb.utils.embedding_functions import OpenAIEmbeddingFunction
from langchain_openai import AzureOpenAIEmbeddings
from embedchain.config import BaseEmbedderConfig
from embedchain.embedder.base import BaseEmbedder
from embedchain.models import VectorDimensions

class OpenAIEmbedder(BaseEmbedder):
    def __init__(self, config: Optional[BaseEmbedderConfig] = None):
        super().__init__(config=config)
        embeddings = AzureOpenAIEmbeddings(
            azure_endpoint=os.environ.get("AZURE_OPENAI_ENDPOINT"),
            api_key=os.environ.get("AZURE_OPENAI_KEY"),
            azure_deployment=os.environ.get("AZURE_OPENAI_DEPLOYMENT_EMBEDDING")
        )
        embedding_fn = BaseEmbedder._langchain_default_concept(embeddings)
        self.set_embedding_fn(embedding_fn=embedding_fn)
        vector_dimension = self.config.vector_dimension or VectorDimensions.OPENAI.value
        self.set_vector_dimension(vector_dimension=vector_dimension)
`

**Comment by kaushalpowar** [comment]
> Hey @kaushalpowar, I think the new version of crewai gives you the flexibility to change the embedding and LLM via a configuration. please check the latest docs. in case, you can change for some reason, this is what i did.
> 
> navigate to this file : lib/python3.11/site-packages/embedchain/embedder/openai.py
> 
> replace the content with the below
> 
> `import os from typing import Optional from chromadb.utils.embedding_functions import OpenAIEmbeddingFunction from langchain_openai import AzureOpenAIEmbeddings from embedchain.config import BaseEmbedderConfig from embedchain.embedder.base import BaseEmbedder from embedchain.models import VectorDimensions
> 
> class OpenAIEmbedder(BaseEmbedder): def **init**(self, config: Optional[BaseEmbedderConfig] = None): super().**init**(config=config) embeddings = AzureOpenAIEmbeddings( azure_endpoint=os.environ.get("AZURE_OPENAI_ENDPOINT"), api_key=os.environ.get("AZURE_OPENAI_KEY"), azure_deployment=os.environ.get("AZURE_OPENAI_DEPLOYMENT_EMBEDDING") ) embedding_fn = BaseEmbedder._langchain_default_concept(embeddings) self.set_embedding_fn(embedding_fn=embedding_fn) vector_dimension = self.config.vector_dimension or VectorDimensions.OPENAI.value self.set_vector_dimension(vector_dimension=vector_dimension) `

Thank you
