### ISSUE TITLE
missing value in tasks

### ISSUE THREAD

**Issue by Prathviraj98** [joaomdmoura/crewAI-examples#74]
ValidationError: 1 validation error for Task expected_output Field required [type=missing, input_value={'description': 'how to f...'async_execution': True}, input_type=dict] For further information visit https://errors.pydantic.dev/2.6/v/missing

**Comment by VishalxRana** [comment]
Hey @Prathviraj98, would like to know how this issue was resolved. Facing the same problem.

**Comment by Prathviraj98** [comment]
It's been updated and they added more parameters to the function so if you
wanna stick to the old /"your current" state of code downgrade crewai to
0.10.0 (it might downgrade some langchain libs too if it doesn't and you
get errors try downgrading langchain tools or switch from langchain
community to experimental)
