### ISSUE TITLE
How to increase agent max iteration limit

### ISSUE THREAD

**Issue by matsuobasho** [joaomdmoura/crewAI-examples#9]
I was running the trip planner with a local LM and got the following output:

```
> Finished chain.
Task output: Agent stopped due to max iterations.


########################
## Here is you Trip Plan
########################

Agent stopped due to max iterations.
```

Where can I increase the threshold for the max iterations?

**Comment by MindsightsAI** [comment]
Same problem

**Comment by Biancamazzi** [comment]
If you haven't solved it yet, could you please create an issue at https://github.com/joaomdmoura/crewAI/issues? Let's focus on addressing issues there.

**Comment by matsuobasho** [comment]
Yes, this has been resolved in this issue (https://github.com/joaomdmoura/crewAI/issues/65) and is part of release 0.1.32.  Thanks
